language: generic

dist: bionic

## Uncomment the following lines if you require extra dependencies
#before_install:
# - sudo apt-get install ghostscript # If you use latex > dvips > ps2pdf
# - sudo apt-get install python-pygments # If you use the minted package
  # If you use custom fonts:
# - mkdir $HOME/.fonts
# - cp -a $TRAVIS_BUILD_DIR/src/fonts/. $HOME/.fonts/
# - fc-cache -f -v

install:
  - mkdir texlive
  - cd texlive
  - wget https://raw.githubusercontent.com/NikolasMiz/travis-ci-latex-pdf/master/4-texlive/texlive/texlive_install.sh
  - wget https://raw.githubusercontent.com/NikolasMiz/travis-ci-latex-pdf/master/4-texlive/texlive/texlive_packages
  - wget https://raw.githubusercontent.com/NikolasMiz/travis-ci-latex-pdf/master/4-texlive/texlive/texlive.profile
  - cd ..
  - source ./texlive/texlive_install.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
  - cd esterni/piano-di-progetto
  - latexmk -pdf piano-di-progetto.tex