language: generic
dist: bionic

## Uncomment the following lines if you require extra dependencies
#before_install:
# - sudo apt-get install ghostscript # If you use latex > dvips > ps2pdf
# - sudo apt-get install python-pygments # If you use the minted package
  # If you use custom fonts:
# - mkdir $HOME/.fonts
# - cp -a $TRAVIS_BUILD_DIR/src/fonts/. $HOME/.fonts/
# - fc-cache -f -v

install:
  - mkdir texlive
  - cd texlive
  - wget https://raw.githubusercontent.com/NikolasMiz/travis-ci-latex-pdf/master/4-texlive/texlive/texlive_install.sh
  - wget https://raw.githubusercontent.com/NikolasMiz/travis-ci-latex-pdf/master/4-texlive/texlive/texlive_packages
  - wget https://raw.githubusercontent.com/NikolasMiz/travis-ci-latex-pdf/master/4-texlive/texlive/texlive.profile
  - cd ..
  - source ./texlive/texlive_install.sh
#  - sudo apt-get install texlive-full

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

jobs:
  include:

    - script:
      - cd esterni/analisi-dei-requisiti
      - lualatex --synctex=1 --interaction=nonstopmode --c-style-errors -shell-escape -pdf analisi-dei-requisiti.tex
      - cd ../..
      name: "Analidi dei requisiti"

    - script:
      - cd esterni/glossario
      - lualatex --synctex=1 --interaction=nonstopmode --c-style-errors -shell-escape -pdf glossario.tex
      - cd ../..
      name: "Glossario"

    - script:
      - cd interni/norme-di-progetto
      - lualatex --synctex=1 --interaction=nonstopmode --c-style-errors -shell-escape -pdf norme-di-progetto.tex
      - cd ../..
      name: "Norme di progetto"
    
    - script:
      - cd esterni/piano-di-progetto
      - lualatex --synctex=1 --interaction=nonstopmode --c-style-errors -shell-escape -pdf piano-di-progetto.tex
      - cd ../..
      name: "Piano di progetto"

    - script:
      - cd esterni/piano-di-qualifica
      - lualatex --synctex=1 --interaction=nonstopmode --c-style-errors -shell-escape -pdf piano-di-qualifica.tex
      - cd ../..
      name: "Piano di qualifica"

    - script:
      - cd interni/studio-di-fattibilita
      - lualatex --synctex=1 --interaction=nonstopmode --c-style-errors -shell-escape -pdf studio-di-fattibilita.tex
      - cd ../..
      name: "Studio di fattibilita"
      
    - script:
      - cd esterni/verbali
      - lualatex --synctex=1 --interaction=nonstopmode --c-style-errors -shell-escape -pdf *.tex
      - cd ../..
      name: "Verbali esterni"

    - script:
      - cd interni/verbali
      - lualatex --synctex=1 --interaction=nonstopmode --c-style-errors -shell-escape -pdf *.tex
      - cd ../..
      name: "Verbali interni"

