language: generic
dist: bionic
install:
- mkdir texlive
- cd texlive
- wget https://raw.githubusercontent.com/NikolasMiz/travis-ci-latex-pdf/master/4-texlive/texlive/texlive_install.sh
- wget https://raw.githubusercontent.com/NikolasMiz/travis-ci-latex-pdf/master/4-texlive/texlive/texlive_packages
- wget https://raw.githubusercontent.com/NikolasMiz/travis-ci-latex-pdf/master/4-texlive/texlive/texlive.profile
- cd ..
- source ./texlive/texlive_install.sh
- wget https://raw.githubusercontent.com/NikolasMiz/Dropbox-Uploader/master/dropbox_uploader.sh
- chmod +x dropbox_uploader.sh
cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"
jobs:
  include:
  - script:
    - cd esterni/analisi-dei-requisiti
    - lualatex --synctex=1 --interaction=nonstopmode -shell-escape
      analisi-dei-requisiti.tex
    - cd ../..
    name: Analisi dei requisiti
  - script:
    - cd esterni/glossario
    - lualatex --synctex=1 --interaction=nonstopmode -shell-escape
      glossario.tex
    - cd ../..

    name: Glossario
  - script:
    - cd interni/norme-di-progetto
    - lualatex --synctex=1 --interaction=nonstopmode -shell-escape
      norme-di-progetto.tex
    - cd ../..

    name: Norme di progetto
  - script:
    - cd esterni/piano-di-progetto
    - lualatex --synctex=1 --interaction=nonstopmode -shell-escape
      piano-di-progetto.tex
    - cd ../..
   
    name: Piano di progetto
  - script:
    - cd esterni/piano-di-qualifica
    - lualatex --synctex=1 --interaction=nonstopmode -shell-escape
      piano-di-qualifica.tex
    - cd ../..
    
    name: Piano di qualifica
  - script:
    - cd interni/studio-di-fattibilita
    - lualatex --synctex=1 --interaction=nonstopmode -shell-escape
      studio-di-fattibilita.tex
    - cd ../..
    name: Studio di fattibilita
  - script:
    - cd esterni/verbali
    - for f in *.tex; do lualatex --synctex=1 --interaction=nonstopmode -shell-escape $f; done
    - cd ../..
    
    name: Verbali esterni
  - script:
    - cd interni/verbali
    - for f in *.tex; do lualatex --synctex=1 --interaction=nonstopmode -shell-escape $f; done
    - cd ../..
    
    name: Verbali interni
before_install:
